steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/roava-project/nodejs-cicd:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/roava-project/nodejs-cicd:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'deploy', 'node-on-cloud-run', '--image', 'gcr.io/roava-project/nodejs-cicd:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/roava-project/nodejs-cicd
  
