steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/fastdatacomm/cicd-on-google-cloud-build:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/fastdatacomm/cicd-on-google-cloud-build:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'node-on-cloud-run', '--image', 'gcr.io/fastdatacomm/cicd-on-google-cloud-build:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

  
